# Generated by Django 5.0.2 on 2024-02-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
